apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: projet_docker
type: Opaque
data:
  # echo -n "root_password" | base64
  mysql-root-password: cm9vdF9wYXNzd29yZA==
  # echo -n "contact_password" | base64
  mysql-password: Y29udGFjdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: projet_docker
type: Opaque
data:
  # echo -n "contact_password" | base64
  db-password: Y29udGFjdF9wYXNzd29yZA==